feat: setup the app to start without errors
scorpionka/angular-fundamentals-template-main pull request #1
Opened 2023-09-05 21:54 UTC by scorpionka

2023-09-12 14:53 UTC, UladzislauMazhanau commented on .vscode/launch.json
> +}
It is generally better to include IDE config files in the .gitignore file (in most cases).

2023-09-12 14:53 UTC, UladzislauMazhanau commented on src/app/app.component.ts
> +    }
You should use the `@Output` decorator when you want to make a class field as an output property. In this case, you don't need it and don't use it. Therefore, you can simply change the '`isLogged`' field to the opposite value in the '`login`' method.

2023-09-12 14:53 UTC, UladzislauMazhanau commented on src/app/shared/components/button/button.component.ts
> +  @Input() iconName!: IconName;
According to the requirements, these fields should be optional. Using the Non-null Assertion Operator` '!' ` ([Link](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-0.html#non-null-assertion-operator)) for fields tells TypeScript that we are confident these fields will not be null, and it should not warn us about the possibility of empty values. To make fields optional, you can use optional parameters `'?'.` ([Link](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-0.html#optional-class-properties))

2023-09-12 14:53 UTC, UladzislauMazhanau commented on src/app/shared/components/info/info.component.ts
> +  @Input() text!: string;
According to the requirements, these fields should be optional. Using the Non-null Assertion Operator'!' ([Link](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-0.html#non-null-assertion-operator)) for fields tells TypeScript that we are confident these fields will not be null, and it should not warn us about the possibility of empty values. To make fields optional, you can use optional parameters '?'. ([Link](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-0.html#optional-class-properties))

2023-09-12 14:53 UTC, UladzislauMazhanau commented on src/types.d.ts
> +}
It would be better to rename the file to `course.<interface or model>.ts` (`course.model.ts`) and create a directory for it in `src/app/shared/<interfaces or models>` and place it there. Move it to the shared directory because this interface is used in two modules, `courses.module` and `course-info.module`. Just don't forget to add `export` keyword before declaring the interface and import it wherever it's used (your IDE should highlight the places).

Use `.d.ts` files primarily for declaring types when working with external JavaScript libraries that lack built-in TypeScript support. In such cases, a .d.ts file helps TypeScript understand the types to expect when working with that library.

2023-09-12 14:54 UTC, UladzislauMazhanau requested changes
Create a module named `course-info.module.ts`, move the `course-info` component into it, and then add this module to the root module [Link](https://d17btkcdsmqrmh.cloudfront.net/angular-fundamentals/docs/1.1.0/module_2-basic-structure/hometask/task#2-generate-and-implement-feature-components)

2023-09-13 08:48 UTC, scorpionka commented on .vscode/launch.json
> +}
added .vscode/* to .gitignore file

2023-09-13 08:49 UTC, scorpionka commented on src/app/app.component.ts
> +    }
simplified

2023-09-13 08:49 UTC, scorpionka commented on src/app/shared/components/button/button.component.ts
> +  @Input() iconName!: IconName;
fixed

2023-09-13 08:49 UTC, scorpionka commented on src/app/shared/components/info/info.component.ts
> +  @Input() text!: string;
fixed

2023-09-13 08:50 UTC, scorpionka commented on src/types.d.ts
> +}
moved and exported

2023-09-13 08:50 UTC, scorpionka commented
added course-info.module.ts

2023-09-13 08:57 UTC, UladzislauMazhanau commented
Well done!

2023-09-13 08:57 UTC, UladzislauMazhanau approved these changes

2023-09-13 09:00 UTC, merged