Develop task forms
scorpionka/angular-fundamentals-template-main pull request #2
Opened 2023-09-13 21:56 UTC by scorpionka

2023-09-19 14:37 UTC, UladzislauMazhanau requested changes

2023-09-19 14:37 UTC, UladzislauMazhanau commented on src/app/shared/components/course-form/course-form.component.ts
> +  }
For authors, you don't need a separate component and a separate form according to the task conditions. You should have two FormArrays to store the list of authors and the list of course authors, as well as a '`newAuthor`' field that will be a FormGroup. So, the basic structure of the form should look something like this:
```suggestion
this.courseForm = this.fb.group({
      title: ['', [Validators.required, Validators.minLength(2)]],
      description: ['', [Validators.required, Validators.minLength(2)]],
      duration: ["", [Validators.required, Validators.min(1)]],
      authors: this.fb.array([]),
      courseAuthors: this.fb.array([]),
      newAuthor: this.fb.group({
        authorName: ['', [Validators.minLength(2), Validators.pattern('^[a-zA-Z0-9 ]*$')]]
      })
    });
```
 When we select an author from the '`authors`' list, they are removed from that list and added to the '`courseAuthors`' list. When removed from '`courseAuthors`', they return to the '`authors`' array. To work with FormArrays, you can refer to this article - [[link](https://netbasal.com/angular-reactive-forms-the-ultimate-guide-to-formarray-3adbe6b0b61a) If you are using the 'input' tag to display values from the authors' list, consider using the 'disabled' attribute like this: [disabled]="true".]. For working with a nested FormGroup ('newAuthor'), you can refer to this article - [[link](https://angular.io/api/forms/FormGroupName#register-a-nested-formgroup)].

2023-09-19 14:42 UTC, UladzislauMazhanau commented
[Optional] It would be great if you also covered styles for fields in the 'ng-invalid' state since it's a common practice when working with forms. In your current setup, fields always start with the 'ng-invalid' state, and the user sees everything in red even before entering any data or interacting with the form, which is not ideal.

2023-09-25 03:46 UTC, scorpionka commented on src/app/shared/components/course-form/course-form.component.ts
> +  }
done

2023-09-25 03:51 UTC, scorpionka commented on src/app/shared/components/registration-form/registration-form.component.ts
> +  }
done

2023-09-25 03:54 UTC, scorpionka commented on src/app/shared/components/course-form/course-form.component.html
> +    <div class="course" class="course-form">
fixed

2023-09-25 03:55 UTC, scorpionka commented on src/app/shared/components/course-form/course-form.component.html
> +      <div class="form__control" class="half-size">
fixed

2023-09-25 03:56 UTC, scorpionka commented on src/app/shared/components/course-form/course-form.component.html
> +      <div class="form__control" class="half-size">
The implementation was changed.

2023-09-25 03:57 UTC, scorpionka commented on src/app/shared/components/course-form/course-form.component.html
> +<div class="form__action" class="course-form-button">
fixed

2023-09-25 03:59 UTC, scorpionka commented on src/app/shared/components/login-form/login-form.component.html
> +            name="email"
The duplicate was removed.

2023-09-25 04:00 UTC, scorpionka commented on src/app/shared/components/login-form/login-form.component.html
> +        <div class="form__action" class="login-submit-button">
fixed

2023-09-25 04:02 UTC, scorpionka commented on src/app/shared/components/registration-form/registration-form.component.html
> +    <div class="form__action" class="registration-form-button">
fixed

2023-09-25 05:29 UTC, scorpionka commented on src/app/shared/components/course-form/course-form.component.html
> +          <div class="course__duration">{{ durationValue! | duration }}</div>
fixed

2023-09-25 06:05 UTC, scorpionka commented on src/app/shared/components/registration-form/registration-form.component.ts
> +      email: ["", [Validators.required]],
added

2023-09-25 06:05 UTC, scorpionka commented on src/app/shared/components/registration-form/registration-form.component.html
> +          appEmailValidator="[a-z0-9]+@[a-z]+.[a-z]{2,3}"
removed

2023-09-25 10:42 UTC, scorpionka commented on src/app/shared/components/course-form/course-form.component.ts
> +  }
done

2023-09-26 10:53 UTC, UladzislauMazhanau commented on src/app/shared/components/login-form/login-form.component.html
> +          </span>
Better not to use block-level elements like `<div>` inside an inline element like `<span>`. In your case, it's better to do the opposite and use `<span>` inside `<div>`. Also, in order not to display multiple errors at the same time, you can use `ngIf` like this : `<div *ngIf="condition; else elseBlock">Content to render when condition is true.</div>
<ng-template #elseBlock>Content to render when condition is false.</ng-template>` ([Link](https://angular.io/api/common/NgIf#description))

2023-09-26 10:53 UTC, UladzislauMazhanau commented
Good job!

2023-10-01 21:53 UTC, merged